# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20160509_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='age',
        ),
    ]
