# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_auto_20160510_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eye_surgery', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('eye_surgery_description', models.TextField(default=None, max_length=500, null=True)),
                ('medication', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('medication_description', models.TextField(default=None, max_length=500, null=True)),
                ('head_injury', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('seizure_epilepsy', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('eye_problems', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('heart_problems', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('heart_procedures', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('high_blood_pressure', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('high_cholesterol', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('chronic_breathing_problems', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('lung_disease', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('kidney_problems', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('stomach_liver_digestive_problems', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('diabetes_blood_sugar_problems', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('insulin_used', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('mental_health_problems', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('fainting_passing_out', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('dizziness_headaches', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('unexplained_weight_loss', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('stroke', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('missing_limited_use_limbs', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('neck_back_problems', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('bone_muscle_joint', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('blood_clots_bleeding_problems', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('cancer', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('chronic_infection_diseases', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('sleep_disorders', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('had_sleep_test', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('spent_night_hospital', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('broken_bone', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('tabacco_use', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('currently_drink_alcohol', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('used_illegal_substances', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('failed_drug_test_dependent_illegal_substance', models.CharField(choices=[('Yes', 'yes'), ('No', 'no'), ('Not Sure', 'not sure')], default='no', max_length=10)),
                ('date_completed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 10, 19, 30, 34, 706385)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='registration_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 10, 19, 30, 43, 659091)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 10, 19, 30, 53, 699099)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverhistory',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver'),
        ),
    ]
