# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_auto_20160510_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='clp_cdl_applicant_holder',
            field=models.BooleanField(default=False),
        ),
    ]
