# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0003_auto_20160608_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodpressure',
            name='exam_questions',
        ),
        migrations.RemoveField(
            model_name='examdetermination',
            name='exam_questions',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='examiner',
        ),
        migrations.RemoveField(
            model_name='physicalexam',
            name='exam_questions',
        ),
        migrations.RemoveField(
            model_name='urinalysis',
            name='exam_questions',
        ),
        migrations.RemoveField(
            model_name='vision',
            name='exam_questions',
        ),
    ]
