# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0004_auto_20160609_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='honorific',
            field=models.CharField(choices=[(b'Dr.', b'Dr.'), (b'Mr.', b'Mr.'), (b'Mrs.', b'Mrs.'), (b'Ms.', b'Ms.')], default=b'DR.', max_length=200),
        ),
    ]
